### PR TITLE
Updating to Swift 5.0 and RxSwift 5.0

### PR DESCRIPTION
**Pull request by Ravi61**
Changes include
1. Updating Cartfile
2. Removing public access level from `var stream` as it is already present in a public extension.
3. RxSwift moved to DispatchTimeInterval from TimeInterval, leading to the change in test cases.
4. General Build Settings update as suggested by Xcode.

### CODE REVIEW

**Comment by Ravi61** [comment]
@fjcaetano what went wrong here? 👇

**Review by fjcaetano — COMMENTED** [review]
Is there anything that we can update in the example project to RxSwift 5.0?

Don't worry about the CI, it recently started to fail because we're parallelizing tests for multiple devices.

**Comment by Ravi61** [comment]
Updated the example project, didn't have any changes related to RxSwift 5.0 but updated the project configurations.

**Comment by fjcaetano** [comment]
@Ravi61 I'm sorry, I assumed the tests failed because of the parallelization without actually checking the CI. That's on me.

It looks like the Carthage installation failed for some reason. It's good that you updated it so it'll run again. Let's wait for the CI to finish running so we can check if everything is okay. I ran your branch on my machine and the tests passed.

**Comment by fjcaetano** [comment]
I think I have an idea of what might be failing, you'll need to update `.travis.yml` to use Xcode 10.2

**Comment by Ravi61** [comment]
@fjcaetano Let me know what do I have to update in `.travis.yml`. I am assuming `osx_image: xcode10.1` to `osx_image: xcode10.2`, right?

**Comment by fjcaetano** [comment]
@Ravi61 yes, that should be enough

**Comment by mariohahn** [comment]
Any Ideas what's wrong?

**Comment by fjcaetano** [comment]
Travis failed when linting the pod library. I tried updating the podspec file, but it kept failing. Are you being able to use RxWebSockets with Swift 5 if you point to this PR's branch? If so, I'll hold this open for a bit while I investigate what might be happening.

However, let me know if you're not able to use the project and I'll merge the PR as-is and work on a fix later.

**Pull request merged**
